# Generated by Django 5.2.4 on 2025-08-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainview', '0005_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rent',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
